{
 "title": "Gemfire Management Console",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(gemfire_gets{group=\"servers\"}, instance)"
    }
   },
   { "name": "gemfire_job_name", "query": "gemfire_cluster" }
  ]
 },
 "panels": [
  { "title": "TCP Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "tcpExtListenOverflows",
   "type": "timeseries",
   "description": "Number of times a TCP socket’s listen queue completely filled up and had to drop a connection. Useful for determining if SYN cookie protection is affecting performance.\n\nThis counts the number of times the listen queue for a socket overflowed. When a server socket is listening for connections, it maintains a queue (called the accept queue or listen queue) of completed connections waiting to be accepted by the application. When this queue fills up and new connections arrive, those connections can't be queued and this counter increments. This typically happens when an application isn't calling accept() fast enough to process incoming connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_tcpExtListenOverflows{job=\"$gemfire_job_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tcpExtListenDrops",
   "type": "timeseries",
   "description": "This counts connection attempts that were dropped due to various listen-related issues. This includes cases where the listen queue is full (which would also increment ListenOverflows), but can also include other scenarios like memory allocation failures when trying to handle new connections, or other resource constraints during the connection establishment process.\n\nListenOverflows is specifically about queue overflow situations\nListenDrops is broader and includes overflows plus other drop reasons\n\nListenDrops >= ListenOverflows",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_tcpExtListenDrops{job=\"$gemfire_job_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tcpExtSynCookiesSent",
   "type": "timeseries",
   "description": "Counts of tcpExtSynCookies sent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "gemfire_tcpExtSynCookiesSent{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "tcpExtSynCookiesRecv",
   "type": "timeseries",
   "description": "Counts of tcpExtSynCookies received.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "gemfire_tcpExtSynCookiesRecv{}", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Gets Throughput",
   "type": "timeseries",
   "description": "This chart displays the throughput of all 'Get' operations performed across the entire cache.\nRIGHT Axis (RED): The 'Get' operation requests by the remote Client applications.\nLEFT Axis (BLUE): The 'Get' operation requests by the remote Client applications and distributed get operations.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(gemfire_getRequests{job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "Client Gets Rate"
    },
    {
     "expr": "sum(rate(gemfire_gets{job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "All Gets"
    }
   ]
  },
  {
   "title": "Average Get Latency",
   "type": "timeseries",
   "description": "Average Get Latency presents the total time taken by all 'Get' operations performed across the cluster divided by the number of all 'Get' operations performed across the cluster to get an average time taken per 'Get' operation in the system.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(gemfire_getTime{job=\"$gemfire_job_name\"}[$__rate_interval])) / sum(rate(gemfire_gets{job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "Average Get Latency"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "description": "Ratio of cache hits to total data requests ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_gets{group=\"servers\", instance=~\"RegionStats.*|cachePerfStats\", job=\"$gemfire_job_name\"})\n/\nsum(gemfire_gets{group=\"servers\", instance=~\"RegionStats.*|cachePerfStats\", job=\"$gemfire_job_name\"} + \n    gemfire_misses{group=\"servers\", instance=~\"RegionStats.*|cachePerfStats\", job=\"$gemfire_job_name\"})\n* 100",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "description": "This metric represents the rate of Get operations across the entire cluster that resulted in a matched key per second.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gemfire_getRequests{job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "description": "This chart represents the rate of Get operations that resulted in a miss, where the key that was requested was not in the cache per second.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(gemfire_misses{job=\"$gemfire_job_name\"}[$__rate_interval]))\n",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "Average Put Latency",
   "type": "timeseries",
   "description": "Average Put Latency presents the total time taken by all 'Put' operations performed across the cluster divided by the number of all 'Put' operations performed across the cluster to get an average time taken per 'Put' operation in the system.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(gemfire_putTime{job=\"$gemfire_job_name\"}[$__rate_interval])) / sum(rate(gemfire_puts{job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "Average Put Latency "
    }
   ]
  },
  {
   "title": "Puts Throughput",
   "type": "timeseries",
   "description": "This chart displays the throughput of all 'Put' operations performed across the entire cache.\nRIGHT Axis (RED): The 'Put' operation requests by the remote Client applications.\nLEFT Axis (BLUE): The 'Put' operation requests by the remote Client applications and distributed put operations.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(gemfire_putRequests{job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "Client Put Requests"
    },
    {
     "expr": "sum(rate(gemfire_puts{job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "Puts"
    }
   ]
  },
  {
   "title": "Function Execution Detail",
   "type": "timeseries",
   "description": "RED (RIGHT AXIS): Function Execution Queue size. If this size continues to grow, then there is an issue with one of the members that should be addressed.\nBLUE (LEFT AXIS): A calculated rate based on functionExecutionCalls-functionExecutionsCompleted, which provide the output of failed function execution calls per second.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gemfire_functionExecutionCalls{group=\"servers\", category=\"FunctionStatistics\", exported_instance!~\"^(FunctionExecution|distributionStats|.internal.)$\", member!~'.:locator.', job=\"$gemfire_job_name\"}) - sum(gemfire_functionExecutionsCompleted{group=\"servers\", category=\"FunctionStatistics\", exported_instance!~\"^(FunctionExecution|distributionStats|.internal.)$\", member!~'.:locator.', job=\"$gemfire_job_name\"})",
     "legendFormat": "Uncompleted Execution Rate"
    },
    {
     "expr": "sum(gemfire_functionExecutionQueueSize{group=\"servers\", member!~'.:locator.', job=\"$gemfire_job_name\"})",
     "legendFormat": "Function Queue"
    }
   ]
  },
  {
   "title": "Client Put Request Rate by Server",
   "type": "timeseries",
   "description": "For Each Server Member, this chart represents the rate of requests of put operations received per second on a specific member.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by(member) (rate(gemfire_puts{group=\"servers\", category=\"CachePerfStats\", job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Region Overcapacity",
   "type": "timeseries",
   "description": "For persistent regions that hold data in memory and on disk, we provide this chart to ensure that these values stay. Issue(s): If entries on disk exceed the number that is on the VM, the ability to recover from disk is at risk. Action(s): To prevent future recovery failures, scale up and increase the memory available to servers.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (instance) (gemfire_entriesOnlyOnDisk{group=\"servers\", job=\"$gemfire_job_name\"}))- (sum by (instance) (gemfire_entriesInVM{group=\"servers\", job=\"$gemfire_job_name\"}))",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "Message Queue Size",
   "type": "timeseries",
   "description": "The GemFire message queue represents the size of the operations, such as Get, Put, Destroy, and so on, subscription queue.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_messageQueueSize{group=\"servers\", job=\"$gemfire_job_name\"}",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "Client Query Rate",
   "type": "timeseries",
   "description": "The GemFire query rate is the number of cache client operations query requests performed per second.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(member) (rate(gemfire_queryRequests{group=\"servers\", job=\"$gemfire_job_name\"}[$__rate_interval])) ",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Average Query Time",
   "type": "timeseries",
   "description": "The average query time is computed by taking the total time of all query requests (processQueryTime) and dividing it by the number of requests (queryRequests), to get an average time spent on any given query.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_processQueryTime{group=\"servers\", job=\"$gemfire_job_name\"} / (gemfire_queryRequests{group=\"servers\", job=\"$gemfire_job_name\"} > 0) or vector(0)",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "Region Details",
   "type": "table",
   "description": "This table shows the type, name, and entry count for each region in the cache.\nFor convenience, we have summarized the Partitioned regions with the Partition Total rows",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum by (region, data_policy, member, custom_type) (label_replace(gemfire_cache_entries{job=\"$gemfire_job_name\", data_policy!~\".*PARTITION.*\" }, \"custom_type\", \"REPLICATE\", \"\", \"\"))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (region, data_policy, member, custom_type) (label_replace(gemfire_cache_entries{job=\"$gemfire_job_name\", data_policy!~\".*REPLICATE.*\" }, \"custom_type\", \"PARTITIONED\", \"\", \"\"))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (region, data_policy, custom_type) (label_replace(gemfire_cache_entries{job=\"$gemfire_job_name\", data_policy=~\".*PARTITION.*\" }, \"custom_type\", \"PARTITION TOTAL\", \"\", \"\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Server Old Gen Utilization",
   "type": "timeseries",
   "description": "JVM Heap Usage across all cluster members",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_jvm_memory_used_bytes{area='heap', member_type='server', id!='Par Eden Space', id!='Par Survivor Space', job=\"$gemfire_job_name\"} / gemfire_jvm_memory_max_bytes{area='heap', member_type='server', id!='Par Eden Space', id!='Par Survivor Space', job=\"$gemfire_job_name\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "bargauge",
   "description": "Disk utilization by member in the cluster. The percentage remaining is computed by utilizing the statistics gathered by GemFire from the underlying system. Some operating systems (like macOS) do not emit these metrics and will cause this graph to be empty.\n\nGemFire stats: volumeFreeSpace, volumeSize\n\nIssue(s): Disks are needed for proper operation or restoration of a cluster, logging, and persisted data either from overflow or persistent regions. There may be a degradation of service or possible data loss if disks on any member get full.\n\nAction(s): Evaluate log size and consider a change to a rolling scheme if not already in place.\nConsider modifying persistent data or overflow triggers.\nConsider adding a new member, scaling horizontally.\nConsider increasing the default storage capacity of members, scaling vertically.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gemfire_volumeSize{category=\"DiskDirStatistics\", group=\"servers\", job=\"$gemfire_job_name\"} - gemfire_volumeFreeSpace{category=\"DiskDirStatistics\", group=\"servers\", job=\"$gemfire_job_name\"}) / gemfire_volumeSize{category=\"DiskDirStatistics\", group=\"servers\", job=\"$gemfire_job_name\"} * 100",
     "legendFormat": "{{instance}} - {{member}}"
    }
   ]
  },
  {
   "title": "CPU Utilization % by Member",
   "type": "timeseries",
   "description": "CPU utilization across all nodes",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_cpuActive{job=\"$gemfire_job_name\"}",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Current Client Connections by Member",
   "type": "timeseries",
   "description": "This chart displays a line for each server in the cluster and represents the number of external clients connected to that member.\n\nGemFire stat: currentClientConnections\n\nIssue(s): A high number of connections on one server may indicate improper data balance or load balancing by the system.\n\nAction(s): Consider running a rebalance command.\nConsider evaluating hashing algorithms for entry keys of partitioned data.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gemfire_currentClientConnections{job=\"$gemfire_job_name\"}",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Sampler Delay Duration",
   "type": "timeseries",
   "description": "Delay duration measures the actual time (in ms) the GemFire statistics sampler slept. It calculates the difference between when it went to sleep and when it woke up to sample. Sample time shows how long it took to collect the sample after it woke up.\n\nIssue(s): A heavy load on the server would cause the delayDuration and sampleTime to be different than a typical 1 second measurement. The bigger this number gets, the more likely it is that the server will be under performing and possibly fail.\n\nAction(s): Consider scaling out to handle the increased load if it is encountered.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gemfire_delayDuration{job=\"$gemfire_job_name\"}",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Cluster Communication Delays",
   "type": "timeseries",
   "description": "Delay duration measures the actual time (in ms) the GemFire statistics sampler slept. It calculates the difference between when it went to sleep and when it woke up to sample. Sample time shows how long it took to collect the sample after it woke up.\n\nIssue(s): A heavy load on the server would cause the delayDuration and sampleTime to be different than a typical 1 second measurement. The bigger this number gets, the more likely it is that the server will be under performing and possibly fail.\n\nAction(s): Consider scaling out to handle the increased load if it is encountered.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min(gemfire_replyWaitsInProgress{job=\"$gemfire_job_name\"}, 0) ",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "IO Waits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "gemfire_iowait{category=\"LinuxSystemStats\", job=\"$gemfire_job_name\"}",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "description": "GemFire monitors the AbandonedReadRequests from the cache server.\n\nIssue(s): If this number increases at a fast rate, there might be an issue with the network or the client app.\n\nAction(s): Consider investigating any new client app recently deployed against this cluster.\n\nConsider investigating any new networking changes within this environment.",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gemfire_abandonedReadRequests{job=\"$gemfire_job_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Steal Values",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_cpuSteal{category=\"LinuxSystemStats\", job=\"$gemfire_job_name\"}) by (member) ",
     "legendFormat": "{{member}} "
    }
   ]
  },
  { "title": "WAN Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "WAN Receiver Throughput",
   "type": "timeseries",
   "description": "This chart shows all of the Gateway Receivers for this cluster and the rate of bytes/second that are sent (red) or received (blue).\nIssue(s):\nIf your WAN connected clusters fail, then you will only see a red line as the rate of received (blue) bytes will be zero.\nAction(s):\nInvestigate the connected cluster to better understand why you are no longer receiving bytes from it.",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(gemfire_receivedBytes{job=\"$gemfire_job_name\",category=\"GatewayReceiverStatistics\"}[$__rate_interval]))",
     "legendFormat": "Received bytes {{member}}"
    },
    {
     "expr": "sum(rate(gemfire_sentBytes{job=\"$gemfire_job_name\",category=\"GatewayReceiverStatistics\"}[$__rate_interval]))",
     "legendFormat": "Sent bytes {{member}}"
    }
   ]
  },
  {
   "title": "WAN Sender Queue",
   "type": "timeseries",
   "description": "This graph displays the rate (messages/second) at which a Gateway Sender is able to send events to a WAN connected cluster.",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "rate(gemfire_eventsQueued{job=\"$gemfire_job_name\", category=\"GatewaySenderStatistics\"}[$__rate_interval]) OR vector(0)",
     "legendFormat": "Messages per Second {{member}}"
    }
   ]
  }
 ]
}